language: node_js
node_js:
- '0.10'
script:
- npm run lint
- npm test
after_success:
- npm run coveralls
env:
  global:
    secure: DZhBiqhGiAtn0Ho2dx6gpmgAHjxrKXwy85Ivzr+8we79gGaqyo2vVUdDUAUm+3c0UxDkWLrUOQHcoAxM87CWIDGB7LhNDg7MEz0ZeUVPnkT19Qp6yCG7iK0+I/UE8Igsi5iCE55Nl1c5xv6kth/HI1QsOuB3u3S91t1H5ktZYAU=
deploy:
  provider: npm
  email: kristofer@sommestad.com
  api_key:
    secure: GBHAKhFa92scTx+Y1Ju5avlrGOHOeOmoBLe1tMO7VMR6GWb+YpCt7ijM15vD2/4slBms3b9WZ7sRk76MOErrZkVr7fv5kunomVaSf1QKJw1/hkr2YOx7r0x2WIeMD/TjjypvuQcVvs8aHbM1gC76pothpPxawZsAM3M9Ys3YBnk=
  on:
    tags: true
    repo: Springworks/node-tsheets-client
    all_branches: true
